default_language_version:
  python: python3.11.8

default_stages: [commit, push]

repos:
  - repo: https://github.com/pycqa/isort
    rev: 5.13.2
    hooks:
      - id: isort
        args:
          - "--profile"
          - "black"
          - --line-length=115
  - repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
      - id: codespell
        exclude: >
          (?x)^(
              .*\.yaml|
              .*\.csv|
              .*\.ipynb|
              .*\.lock|
          )$
  - repo: https://github.com/python/black
    rev: 24.2.0
    hooks:
      - id: black
        args:
          - --line-length=115
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
        args:
          - --ignore=E203,W503,E741
          - --max-complexity=30
          - --max-line-length=115
          - --show-source
          - --statistics
